### ISSUE TITLE
Script Hangs (waiting for -y?)

### ISSUE THREAD

**Issue by zimbonz** [Esysc/MDTtools#1]
My MDT task sequence hangs when processing this script - it looks like it is waiting for a -y command. Is there any way around this please?

**Comment by Esysc** [comment]
Hello, could you please tell me which script are you talking about? I'm not maintaining anymore this repo, but if you can give more details I can give a look to the  code.

**Comment by zimbonz** [comment]
Hi,
It is the chocolatey wrapper for mdt script. 
I managed to find the resolution - the script is supposed to look like this:
https://keithga.wordpress.com/2014/11/25/new-tool-chocolatey-wrapper-for-mdt/

See last 5 or six lines, regarding running the command with a "-y" which your script is missing.

**Comment by Esysc** [comment]
Ok I  got now. Well, the script you found here is not exactly the same. The lines you are speaking about have been explicitly removed, because instead to call the wrapper directly, the chocolatey part is managed by a wrapper script. If you open the setup.cmd you ll find the  -y. Basically, instead to declare a software list through mdt initial file, I preferred maintain a .txt file. 

At the beginning of the batch script:
set WINGET=choco update -y   @zimbonz Is this what are you looking for?
